---
name: MacOS

on:
  push:
    branches: main

jobs:
  build-msvc2019:
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: cmake
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B build

      - name: build
        run: cmake --build build --parallel 4
...
