---
name: Ubuntu 

on:
  push:
    branches: master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: cmake
        run: |
            cmake \
            -DCMAKE_CXX_COMPILER=/usr/bin/g++-9 \
            -DCMAKE_BUILD_TYPE=Release \
            -S . \
            -B build

      - name: build
        run: cmake --build build --parallel 4
...
