---
name: Ubuntu

on:
  push:
    branches: main

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: configure-release-build
        run: cmake --preset Linux

      - name: build-release-build
        run: cmake --build build/Linux_build --parallel 4

      - name: configure-debug-build
        run: cmake --preset Linux-debug

      - name: build-debug-build
        run: cmake --build build/Linux_debug_build --parallel 4
...
