name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate build scripts
      run: cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING="Debug" -DTOMBUL_BUILD_TESTS:BOOL=OFF -S . -Bbuild 

    - name: Build
      run: cmake --build build -- --jobs `nproc`
