---
name: Windows

on:
  push:
    branches: main

jobs:
  build-msvc2019:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: configure-release-build_x64
        run: cmake --preset win32-x64

      - name: build-release-build_x64
        run: cmake --build build/win32x64_build --parallel 4

      - name: configure-debug-build_x64
        run: cmake --preset win32-x64-debug

      - name: build-debug-build_x64
        run: cmake --build build/win32x64_debug_build --parallel 4

      - name: configure-release-build_x86
        run: cmake --preset win32-x86

      - name: build-release-build_x86
        run: cmake --build build/win32x86_build --parallel 4

      - name: configure-debug-build_x86
        run: cmake --preset win32-x86-debug

      - name: build-release-build_x86
        run: cmake --build build/win32x86_debug_build --parallel 4

...
