name: windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate build scripts
      run: cmake -DTOMBUL_BUILD_TESTS:BOOL=OFF -S . -Bbuild

    - name: Build
      run: cmake --build build --config Debug
    
