name: windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate build scripts
      run: cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE:STRING="Debug" -DTOMBUL_BUILD_TESTS:BOOL=OFF -S . -Bbuild 

    - name: Build
      run: cmake --build build --target ALL_BUILD --config Debug
